apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.web.config.name }}
  labels:
    release: {{ .Release.Name }}
    {{- toYaml .Values.web.config.labels | nindent 4 }}
data:
  COMMUNITY_SERVICE: {{ .Values.community.proxy_url }}
  IDENTITY_SERVICE: {{ .Values.identity.proxy_url }}
  WORKSHOP_SERVICE: {{ .Values.workshop.proxy_url }}
