# Default values for capi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

jwtSecret: capi
enableLog4j: false
enableShellInjection: true
imagePullPolicy: Always
apiGatewayServiceUrl: https://api.mypremiumdealership.com
apiGatewayServiceInstall: true
apiGatewayPassword: 
tlsEnabled: false

waitForK8sResources:
  image: groundnuty/k8s-wait-for:v1.3
  imagePullPolicy: IfNotPresent

web:
  name: capi-web
  image: crapi/crapi-web
  replicaCount: 1
  port: 80
  sslPort: 443
  service:
    name: capi-web
    labels:
      app: capi-web
    nodePort: 30080
    sslNodePort: 30443
  config:
    name: capi-web-configmap
    labels:
      app: capi-web
  resources:
    limits:
      cpu: "500m"
    requests:
      cpu: 256m
  deploymentLabels:
    app: capi-web
  podLabels:
    app: capi-web
  deploymentSelectorMatchLabels:
    app: capi-web
  serviceSelectorLabels:
    app: capi-web

identity:
  name: capi-identity
  image: crapi/crapi-identity
  port: 8080
  replicaCount: 1
  service:
    name: capi-identity
    labels:
      app: capi-identity
  jwtKeySecret:
    name: jwt-key-secret
    file: keys/jwks.json
    labels:
      app: capi-identity
  config:
    name: capi-identity-configmap
    labels:
      app: capi-identity
    postgresDbDriver: postgresql
    appName: "capi-identity"
    mailhogDomain: "example.com"
    smtpHost: "smtp.example.com"
    smtpPort: 587
    smtpEmail: "user@example.com"
    smtpPass: "xxxxxxxxxxxxxx"
    smtpFrom: "no-reply@example.com"
    smtpAuth: true
    smtpStartTLS: true
    keyStoreType: PKCS12
    keyStore: classpath:certs/server.p12
    keyStorePassword: passw0rd
    keyPassword: passw0rd
    keyAlias: identity
  resources:
    limits:
      cpu: "500m"
    requests:
      cpu: 256m
  deploymentLabels:
    app: capi-identity
  podLabels:
    app: capi-identity
  deploymentSelectorMatchLabels:
    app: capi-identity
  serviceSelectorLabels:
    app: capi-identity

community:
  name: capi-community
  image: crapi/crapi-community
  port: 8087
  replicaCount: 1
  service:
    name: capi-community
    labels:
      app: capi-community
  config:
    name: capi-community-configmap
    labels:
      app: capi-community
    postgresDbDriver: postgres
    mongoDbDriver: mongodb
  resources:
    limits:
      cpu: "500m"
    requests:
      cpu: 256m
  deploymentLabels:
    app: capi-community
  podLabels:
    app: capi-community
  deploymentSelectorMatchLabels:
    app: capi-community
  serviceSelectorLabels:
    app: capi-community

workshop:
  name: capi-workshop
  image: crapi/crapi-workshop
  port: 8000
  replicaCount: 1
  service:
    name: capi-workshop
    labels:
      app: capi-workshop
  config:
    name: capi-workshop-configmap
    labels:
      app: capi-workshop
    postgresDbDriver: postgres
    mongoDbDriver: mongodb
    secretKey: capi
  resources:
    limits:
      cpu: "256m"
    requests:
      cpu: 256m
  deploymentLabels:
    app: capi-workshop
  podLabels:
    app: capi-workshop
  deploymentSelectorMatchLabels:
    app: capi-workshop
  serviceSelectorLabels:
    app: capi-workshop

mailhog:
  name: mailhog
  image: capi/mailhog
  webPort: 8025
  smtpPort: 1025
  replicaCount: 1
  minReadySeconds: 10
  progressDeadlineSeconds: 600
  namespace: capi
  smtpService:
    name: mailhog
    labels:
      app: mailhog
  webService:
    name: mailhog-web
    labels:
      app: mailhog
    nodePort: 30025
  config:
    name: mailhog-configmap
    labels:
      app: mailhog
    mailhogStorage: mongodb
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 64Mi
  deploymentLabels:
    app: mailhog
  podLabels:
    app: mailhog
  podAnnotations:
    sidecar.traceable.ai/inject: "false"
  deploymentSelectorMatchLabels:
    app: mailhog
  serviceSelectorLabels:
    app: mailhog

mongodb:
  name: mongodb
  image: mongo
  version: 5.0
  imagePullPolicy: IfNotPresent
  port: 27017
  replicaCount: 1
  service:
    name: mongodb
    labels:
      app: mongodb
  config:
    name: mongodb-config
    labels:
      app: mongodb
    mongoUser: admin
    mongoPassword: capisecretpassword
    mongoDbName: capi
    mongoUri: "admin:capisecretpassword@mongodb:27017"
  pvc:
    name: mongodb-pv-claim
    labels:
      app: mongodb
    resources:
      requests:
        storage: 1Gi
  serviceSelectorLabels:
    app: mongodb
  podLabels:
    app: mongodb
  statefulsetLabels:
    app: mongodb
  statefulsetSelectorMatchLabels:
    app: mongodb

postgresdb:
  name: postgresdb
  image: postgres
  version: 14
  imagePullPolicy: IfNotPresent
  port: 5432
  replicaCount: 1
  service:
    name: postgresdb
    labels:
      app: postgresdb
  config:
    name: postgres-config
    labels:
      app: postgresdb
    postgresUser: admin
    postgresPassword: capisecretpassword
    postgresDbName: capi
  pvc:
    name: postgres-pv-claim
    labels:
      app: postgresdb
    resources:
      requests:
        storage: 1Gi
  serviceSelectorLabels:
    app: postgresdb
  podLabels:
    app: postgresdb
  statefulsetLabels:
    app: postgresdb
  statefulsetSelectorMatchLabels:
    app: postgresdb

apiGatewayService:
  name: gateway-service
  image: capi/gateway-service
  port: 443
  replicaCount: 1
  service:
    name: "gateway-service"
    labels:
      app: gateway-service
  config:
    name: gateway-service
    labels:
      app: gateway-service
  resources:
    limits:
      cpu: "100m"
    requests:
      cpu: 50m
  deploymentLabels:
    app: gateway-service
  podLabels:
    app: gateway-service
  deploymentSelectorMatchLabels:
    app: gateway-service
  serviceSelectorLabels:
    app: gateway-service
